### ISSUE TITLE
react native web unitlessNumber.js issue with nativewind/babel

### ISSUE THREAD

**Issue by redappleorigin** [marklawlor/nativewind#176]
Hi, I'm using expo with the typescript template created today using the create-expo-app.

When that babel change happens I get the following error:

Uncaught TypeError: Cannot read properties of undefined (reading 'create')
    at ./node_modules/react-native-web/dist/exports/StyleSheet/compiler/unitlessNumbers.js (unitlessNumbers.js:77:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-web/dist/exports/StyleSheet/compiler/normalizeValueWithProperty.js (normalizeValueWithProperty.js:9:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-web/dist/exports/StyleSheet/compiler/createReactDOMStyle.js (index.js:20:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-web/dist/exports/StyleSheet/compiler/index.js (hyphenateStyleName.js:26:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-web/dist/exports/StyleSheet/index.js (index.js:77:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-web/dist/modules/createDOMProps/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-web/dist/exports/createElement/index.js (index.js:9:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-web/dist/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/nativewind/dist/styled/use-interaction.js (use-interaction.js:5:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/nativewind/dist/styled/index.js (index.js:5:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/nativewind/dist/index.js (index.js:18:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at Module.<anonymous> (AppEntry.js:5:1)
    at ./node_modules/expo/build/Expo.fx.web.js (Expo.fx.web.tsx:51:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/build/launch/registerRootComponent.js (registerRootComponent.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (app.tsx:33:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
    
    It's just the default expo app, with the nativewind stuff on top.

**Comment by marklawlor** [comment]
Can you please provide a reproduction

**Comment by redappleorigin** [comment]
Yes sir, I will do so in a few hours

**Comment by redappleorigin** [comment]
Not as default as I intended, but here is a repo showing the issue:

https://github.com/redappleorigin/nativewind-example

**Comment by redappleorigin** [comment]
well darn, if I run without using docker it works fine. It's likely something to do with my docker setup. Sorry for wasting your time like this. If you know docker and have advice, I'd appreciate it, but otherwise, you can close this down. Sorry again about this.

**Comment by redappleorigin** [comment]
Well, after making no changes at all, I delete the whole thing and checked it back out locally, running it in docker and it worked. So... I'm closing this since your work is self healing.
