### ISSUE TITLE
How to Unit Test With Native Wind?

### ISSUE THREAD

**Issue by mikefisher84** [marklawlor/nativewind#290]
**Describe the bug**
I'm trying to write unit tests with react-native, nativewind, Typescript, Jest and @testing-library/reactnative. I have a simple test that should work fine but for the life of me I can't get it to pass and throws an odd error. 

Source Code: 

```ts
import React from 'react'
import { styled } from 'nativewind'
import { TextProps, Pressable, PressableProps, View } from 'react-native'

export type ButtonProps = PressableProps & {
  textStyle?: TextProps['style']
  children?: JSX.Element | JSX.Element[] | string
}

export default styled(({ textStyle, children, ...props }: ButtonProps) => {
  return (
    <Pressable {...props}>
      <View style={textStyle}>{children}</View>
    </Pressable>
  )
}, 'text-indigo-50')

```

Test Code: 

```ts
import React from 'react'
import Button from './Button'
import { render } from '@testing-library/react-native'

describe('<Button />', () => {
  it('exists', () => {
    const button = render(<Button>Test</Button>)
    expect(button).toBeTruthy()
  })
})

```

run the test and it outputs

```
 FAIL  components/button/Button.test.tsx
  <Button />
    ✕ exists (21 ms)

  ● <Button /> › exists

    TypeError: Cannot read properties of null (reading 'useContext')

      at useContext (node_modules/react/cjs/react.development.js:1613:21)
      at Styled (node_modules/nativewind/dist/styled/index.js:24:46)
      at renderWithHooks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6097:18)
      at updateForwardRef (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9704:20)
      at beginWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11710:16)
      at performUnitOfWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15265:12)
      at workLoopSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15201:5)
      at renderRootSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15173:7)
      at performSyncWorkOnRoot (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14880:20)
      at flushSyncCallbacks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2533:22)

  console.error
    Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

       5 | describe('<Button />', () => {
       6 |   it('exists', () => {
    >  7 |     const button = render(<Button>Test</Button>)
         |                          ^
       8 |     expect(button).toBeTruthy()
       9 |   })
      10 | })

      at printWarning (node_modules/react/cjs/react.development.js:209:30)
      at error (node_modules/react/cjs/react.development.js:183:7)
      at resolveDispatcher (node_modules/react/cjs/react.development.js:1587:7)
      at useContext (node_modules/react/cjs/react.development.js:1597:20)
      at Styled (node_modules/nativewind/dist/styled/index.js:24:46)
      at renderWithHooks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6097:18)
      at updateForwardRef (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9704:20)
      at beginWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11710:16)
      at performUnitOfWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15265:12)
      at workLoopSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15201:5)
      at renderRootSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15173:7)
      at performSyncWorkOnRoot (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14880:20)
      at flushSyncCallbacks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2533:22)
      at flushActQueue (../../node_modules/react/cjs/react.development.js:2665:24)
      at actImplementation (../../node_modules/react/cjs/react.development.js:2519:11)
      at node_modules/@testing-library/react-native/src/act.ts:34:25
      at renderWithAct (node_modules/@testing-library/react-native/src/render.tsx:118:3)
      at render (node_modules/@testing-library/react-native/src/render.tsx:47:20)
      at Object.<anonymous> (components/button/Button.test.tsx:7:26)

  console.error
    The above error occurred in the <ForwardRef(NativeWind.NoName)> component:
    
        at Styled (/Users/mike/dev/heir/heir/packages/ui/node_modules/nativewind/dist/styled/index.js:23:34)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

       5 | describe('<Button />', () => {
       6 |   it('exists', () => {
    >  7 |     const button = render(<Button>Test</Button>)
         |                          ^
       8 |     expect(button).toBeTruthy()
       9 |   })
      10 | })

      at logCapturedError (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8409:23)
      at update.callback (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8442:5)
      at callCallback (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3811:12)
      at commitUpdateQueue (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3832:9)
      at commitLayoutEffectOnFiber (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12650:13)
      at commitLayoutMountEffects_complete (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:9)
      at commitLayoutEffects_begin (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13714:7)
      at commitLayoutEffects (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13699:3)
      at commitRootImpl (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15509:5)
      at commitRoot (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15387:5)
      at performSyncWorkOnRoot (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14912:3)
      at flushSyncCallbacks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2533:22)
      at flushActQueue (../../node_modules/react/cjs/react.development.js:2665:24)
      at actImplementation (../../node_modules/react/cjs/react.development.js:2519:11)
      at node_modules/@testing-library/react-native/src/act.ts:34:25
      at renderWithAct (node_modules/@testing-library/react-native/src/render.tsx:118:3)
      at render (node_modules/@testing-library/react-native/src/render.tsx:47:20)
      at Object.<anonymous> (components/button/Button.test.tsx:7:26)
```

Any ideas on what I could be doing wrong would be super helpful. 

Thanks!

**Comment by marklawlor** [comment]
```
 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
```

NativeWind doesn't break the rules of books, so it must be one of the other two reasons
