### ISSUE TITLE
Unable to Test Nativewind Components with Jest

### ISSUE THREAD

**Issue by mikefisher84** [marklawlor/nativewind#310]
**Describe the bug**
I know I had a similar issue quickly closed but I'm pretty confident my issue is with NativeWind. 

I have a ReactNative Component that looks like this. 

```ts
import { styled } from 'nativewind'
const StyledView = styled(View)

export const PostCard: React.FC<{
  post: inferProcedureOutput<AppRouter['post']['all']>[number]
}> = ({ post }) => {
  return (
    <StyledView className="color-slate">
      <Text>{post.title}</Text>
      <Text>{post.content}</Text>
    </StyledView>
  )
}
```

and a test that looks like this: 

```ts
import { PostCard } from './home';
import { render } from '@testing-library/react-native';
import React from 'react';

describe('<HomeScreen />', () => {
  it('<PostCard /> exists', () => {
    const { container } = render(
      <PostCard post={{ id: '1234', title: 'yes', content: 'woo' }} />
    );
    expect(container).toBeTruthy();
  });
});
```

when I run this test in Jest I get this error. 

```
 <HomeScreen /> › <PostCard /> exists

    TypeError: Cannot read properties of null (reading 'useContext')

      at useContext (node_modules/react/cjs/react.development.js:1613:21)
      at NativeWindStyledComponent (node_modules/nativewind/dist/styled/native/index.js:40:53)
      at renderWithHooks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6097:18)
      at updateForwardRef (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9704:20)
      at beginWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11710:16)
      at performUnitOfWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15265:12)
      at workLoopSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15201:5)
      at renderRootSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15173:7)
      at performSyncWorkOnRoot (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14880:20)
      at flushSyncCallbacks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2533:22)
```

However if I run the test again and simply remove the nativewind/tailwind class `color-slate` the test magically passes with no errors. 

My component is very simple and doesn't use anything related to context so I think it may be something regarding Nativewind. 
I've looked on the web and can't find any resources regarding testing React Native apps that use Nativewind with Jest. 

Would be great if you could share some insight on this.

**Comment by mikefisher84** [comment]
After playing with this some more it seems the fix was to upgrade to jest 29 instead of jest 26. However its odd because we're using expo and when running `npx expo install jest` which is supposed to install the correct version for your expo project it installs 26 (I'm on the latest version of expo). When going to jest 29 it fixes Nativewind tests but pnpm throws a peer dependency error.

**Comment by marklawlor** [comment]
I suspect this is more an issue between `@testing-library/react-native` / `jest-expo` and `jest`. This repo has many tests written just like that one and it works without issue. For reference these are the versions being used at time of writing this comment

```
@testing-library/react-native@11.3.0 
jest-expo@46.0.1 
jest@29.2.2
```

I created a branch and added your test to NativeWind's test suite https://github.com/marklawlor/nativewind/blob/issue-310/packages/nativewind/__tests__/issue-340.tsx

This was created using the `next` version detailed in #308

I'm going to move this to a discussion in case other community members have some insight to what is happening
