### ISSUE TITLE
'underline' class crashes NativeWind v3.0.0-next.34

### ISSUE THREAD

**Issue by RaederDev** [marklawlor/nativewind#358]
**Describe the bug**
Adding the className "underline" or even just using `style={{ textDecorationLine: 'underline' }}`  causes a crash in the NativeWind transformer leading to a crash of Metro.

**To Reproduce**
```tsx
<Text
  className="text-menu-small text-center text-grey-dark font-bold underline"
>
  Test
</Text>
```

or

```tsx
<Text
  className="text-menu-small text-center text-grey-dark font-bold"
  style={{ textDecorationLine: 'underline' }}
>
  Test
</Text>
```

**Expected behavior**
No crash

**Additional context**
Log:
```
NativeWind: Rebuilding...
/home/benjamin/projects/censored-app/node_modules/nativewind/dist/postcss/transforms/text-decoration-line.js:40
                    if (nextChild.type === "Identifier" &&
                                  ^

TypeError: Cannot read properties of undefined (reading 'type')
    at textDecorationLine (/home/benjamin/projects/censored-app/node_modules/nativewind/dist/postcss/transforms/text-decoration-line.js:40:35)
    at Object.enter (/home/benjamin/projects/censored-app/node_modules/nativewind/dist/postcss/extract.js:145:74)
    at Object.<anonymous> (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:13:16)
    at walkNode (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:171:36)
    at List.walkReducer (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:197:61)
    at List.reduce (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/utils/List.cjs:176:22)
    at Object.Block (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:105:31)
    at walkNode (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:182:41)
    at walk (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:241:9)
    at getDeclarations (/home/benjamin/projects/censored-app/node_modules/nativewind/dist/postcss/extract.js:124:25)
    at addRule (/home/benjamin/projects/censored-app/node_modules/nativewind/dist/postcss/extract.js:75:55)
    at Object.enter (/home/benjamin/projects/censored-app/node_modules/nativewind/dist/postcss/extract.js:44:21)
    at walkNode (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:171:36)
    at List.walkReducer (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:197:61)
    at List.reduce (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/utils/List.cjs:176:22)
    at Object.StyleSheet (/home/benjamin/projects/censored-app/node_modules/nativewind/node_modules/css-tree/cjs/walker/create.cjs:105:31)

Node.js v19.0.1
```

**Comment by marklawlor** [comment]
@RaederDev Can you check for me the version inside your `node_modules/nativewind/package.json`. This was a bug in a previous release, but it is now covered by unit & integration tests. Additionally the code in your error message no longer exists.

**Comment by RaederDev** [comment]
@marklawlor Thank you for that information, it seems like this was a caching problem with babel. I don't quite understand why but deleting node_modules doesn't solve that issue. But removing it, installing 3.0.0-523465a.0 and then removing and installing 3.0.0-next.34 again seems to finally have done the trick.
