### ISSUE TITLE
TypeError: withNativewind is not a function with expo

### ISSUE THREAD

**Issue by mstronge** [marklawlor/nativewind#564]
**Describe the bug**
When following the instructions on:
https://next.nativewind.dev/quick-starts/expo

When running the expo start command I get the following error:

`
TypeError: withNativewind is not a function
    at Object.<anonymous> (/Users/x/Documents/GitHub/app/metro.config.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at module.exports (/Users/x/Documents/GitHub/app/node_modules/import-fresh/index.js:28:9)
    at loadJs (/Users/x/Documents/GitHub/app/node_modules/cosmiconfig/dist/loaders.js:9:18)
    at Explorer.loadFileContent (/Users/x/Documents/GitHub/app/node_modules/cosmiconfig/dist/createExplorer.js:230:12)
`

**To Reproduce**
Follow the install instructions in the link above.  Versions:
Nativewind: 4.0.0-alpha.7
Tailwind: 3.3.3
Expo SDK: 49.0.11
React Native:  0.72.5

**Expected behavior**
Should be able to start the expo app and have nativewind running.

**Comment by daannet** [comment]
You can find the docs for v4 alpha here: https://www.nativewind.dev/v4/getting-started/metro

**Comment by tyrauber** [comment]
hey, @mstronge, the `next` documentation refers to v3, which has been abandoned in favor of v4.  You can [read about the change here.](https://github.com/marklawlor/nativewind/issues/464). 

The [v4 documentation is here](https://github.com/marklawlor/nativewind/blob/main/apps/website/docs/getting-started/metro.mdx) and an [expo example here](https://github.com/marklawlor/nativewind/tree/main/examples/expo-router). The example works pretty well for 4.0.0-alpha.4, but does not appear to work with 4.0.0-alpha.5-7.

**Note:** V4 / main is actively being developed, with weekly commits, so just be aware that the 4.0.0 releases are clearly alpha, and may have issues.

@marklawlor, is that correct?  Perhaps, with v4 merged into main and ongoing development on main, it might be worth updating the Readme, or stickying an issue with clarification about versions and documentation, and what people should or should not be using?

**Comment by tyrauber** [comment]
That's a way better link to the v4 documentation, @daannet, thank you. Out of curiosity, were you able to get `4.0.0-alpha.5-7` working?

**Comment by marklawlor** [comment]
v4 docs are here https://www.nativewind.dev/v4/overview/
