### ISSUE TITLE
V4: error: Error: ENOENT: no such file or directory, mkdir ''C:\Users\user\app\node_modules\.cache\nativewind\C:\Users\user\app'

### ISSUE THREAD

**Issue by fendyk** [marklawlor/nativewind#620]
**Describe the bug**
When using 4.0.8 (or higher) I get this build error when building my app. it worked fine on my macbook but later when I opened my project on windows it broke.  I cannot find the reason why it suddenly fails. I tried removing cache but the issue persist.

**To Reproduce**
- Remove your `node_modules` and `android` folder.
- Install your dependencies
- Run `expo run:android` 
- Wait for it to build (this should be all good)
- Build completed, now wait for metro to start building your app bundles
- Failed build

**Expected behavior**
Should build the app as intended

**Additional context**
Could this be an `development build` issue? I am **not** using `Expo GO`

Full stacktrace:
```shell
Android Bundling failed 4ms
error: Error: ENOENT: no such file or directory, mkdir 'C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app\node_modules\.cache\nativewind\C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app'
    at mkdirSync (node:fs:1382:3)
    at tailwindCli (C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app\node_modules\nativewind\dist\metro\tailwind-cli.js:33:29)
    at Object.getTransformOptions (C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app\node_modules\nativewind\dist\metro\index.js:53:72)
    at calcTransformerOptions (C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app\node_modules\metro\src\lib\transformHelpers.js:79:50)
    at Object.getTransformFn (C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app\node_modules\metro\src\lib\transformHelpers.js:113:57)
    at IncrementalBundler.buildGraphForEntries (C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app\node_modules\metro\src\IncrementalBundler.js:72:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async IncrementalBundler.buildGraph (C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app\node_modules\metro\src\IncrementalBundler.js:146:19)
    at async C:\Users\raulf\OneDrive\Documenten\GitHub\sport-track-app\node_modules\metro\src\IncrementalBundler.js:187:34  
```

Also this message pops up:
```shell
tailwindcss(native) is taking a long time to build, please read https://tailwindcss.com/docs/content-configuration#pattern-recommendations to speed up your build time
```

My `tailwind.config.js`
```javascript
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './src/components/**/*.{js,jsx,ts,tsx}',
        './src/app/**/*.{js,jsx,ts,tsx}',
    ],
    presets: [require("nativewind/preset")],
    theme: {
        extend: {},
    },
    plugins: []
}
```

My `metro.config.js`
```javascript
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname, { isCSSEnabled: true })

module.exports = withNativeWind(config, { input: './global.css' })
```

My `babel.config.js`
```javascript
module.exports = function (api) {
    api.cache(true);
    return {
        presets: [
            ["babel-preset-expo", {jsxImportSource: "nativewind"}],
            "nativewind/babel",
        ],
        plugins: [
            // Required for expo-router
            'expo-router/babel',
            'react-native-reanimated/plugin'
        ],
    };
};
```

**Comment by marklawlor** [comment]
Fixed in `4.0.10`
