### ISSUE TITLE
v4: Dynamic themes: SyntaxError: Invalid token in pseudo element: WhiteSpace(" ")

### ISSUE THREAD

**Issue by boiboif** [marklawlor/nativewind#626]
**Describe the bug**
After adding plugins configuration according to the document, the project runs with an error message.
`"nativewind": "^4.0.13",`
```
module.exports = {
  ...,
  plugins: [
    // Set a default value on the `:root` element
    ({addBase}) => addBase({':root': '--color-primary: 255 0 0'}),
  ],
};
```

```
SyntaxError: Invalid token in pseudo element: WhiteSpace(" ")
    at cssToReactNativeRuntime (C:\Users\87332\Desktop\project_template\rn_tempalte\node_modules\react-native-css-interop\dist\css-to-rn\index.js:26:34)
    at Socket.<anonymous> (C:\Users\87332\Desktop\project_template\rn_tempalte\node_modules\nativewind\dist\metro\tailwind-cli.js:96:90)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  fileName: 'style.css',
  source: '@cssInterop set darkMode media;\n' +
    '\n' +
    '@cssInterop set nativewind;\n' +
    '\n' +
    ':root: --color-primary: 255 0 0;\n' +
    '\n' +
    '*, ::before, ::after {\n' +
    '  --tw-border-spacing-x: 0;\n' +
    '  --tw-border-spacing-y: 0;\n' +
    '  --tw-translate-x: 0;\n' +
    '  --tw-translate-y: 0;\n' +
    '  --tw-rotate: 0;\n' +
    '  --tw-skew-x: 0;\n' +
    '  --tw-skew-y: 0;\n' +
    '  --tw-scale-x: 1;\n' +
    '  --tw-scale-y: 1;\n' +
    '  --tw-pan-x:  ;\n' +
    '  --tw-pan-y:  ;\n' +
    '  --tw-pinch-zoom:  ;\n' +
    '  --tw-scroll-snap-strictness: proximity;\n' +
    '  --tw-gradient-from-position:  ;\n' +
    '  --tw-gradient-via-position:  ;\n' +
    '  --tw-gradient-to-position:  ;\n' +
    '  --tw-ordinal:  ;\n' +
    '  --tw-slashed-zero:  ;\n' +
    '  --tw-numeric-figure:  ;\n' +
    '  --tw-numeric-spacing:  ;\n' +
    '  --tw-numeric-fraction:  ;\n' +
    '  --tw-ring-inset:  ;\n' +
    '  --tw-ring-offset-width: 0px;\n' +
    '  --tw-ring-offset-color: #fff;\n' +
    '  --tw-ring-color: rgb(59 130 246 / 0.5);\n' +
    '  --tw-blur:  ;\n' +
    '  --tw-brightness:  ;\n' +
    '  --tw-contrast:  ;\n' +
    '  --tw-grayscale:  ;\n' +
    '  --tw-hue-rotate:  ;\n' +
    '  --tw-invert:  ;\n' +
    '  --tw-saturate:  ;\n' +
    '  --tw-sepia:  ;\n' +
    '  --tw-drop-shadow:  ;\n' +
    '  --tw-backdrop-blur:  ;\n' +
    '  --tw-backdrop-brightness:  ;\n' +
    '  --tw-backdrop-contrast:  ;\n' +
    '  --tw-backdrop-grayscale:  ;\n' +
    '  --tw-backdrop-hue-rotate:  ;\n' +
    '  --tw-backdrop-invert:  ;\n' +
    '  --tw-backdrop-opacity:  ;\n' +
    '  --tw-backdrop-saturate:  ;\n' +
    '  --tw-backdrop-sepia:  ;\n' +
    '  --tw-ring-offset-shadow: 0 0 #0000;\n' +
    '  --tw-ring-shadow: 0 0 #0000;\n' +
    '  --tw-shadow: 0 0 #0000;\n' +
    '  --tw-shadow-colored: 0 0 #0000\n' +
    '}\n' +
    '\n' +
    '::backdrop {\n' +
    '  --tw-border-spacing-x: 0;\n' +
    '  --tw-border-spacing-y: 0;\n' +
    '  --tw-translate-x: 0;\n' +
    '  --tw-translate-y: 0;\n' +
    '  --tw-rotate: 0;\n' +
    '  --tw-skew-x: 0;\n' +
    '  --tw-skew-y: 0;\n' +
    '  --tw-scale-x: 1;\n' +
    '  --tw-scale-y: 1;\n' +
    '  --tw-pan-x:  ;\n' +
    '  --tw-pan-y:  ;\n' +
    '  --tw-pinch-zoom:  ;\n' +
    '  --tw-scroll-snap-strictness: proximity;\n' +
    '  --tw-gradient-from-position:  ;\n' +
    '  --tw-gradient-via-position:  ;\n' +
    '  --tw-gradient-to-position:  ;\n' +
    '  --tw-ordinal:  ;\n' +
    '  --tw-slashed-zero:  ;\n' +
    '  --tw-numeric-figure:  ;\n' +
    '  --tw-numeric-spacing:  ;\n' +
    '  --tw-numeric-fraction:  ;\n' +
    '  --tw-ring-inset:  ;\n' +
    '  --tw-ring-offset-width: 0px;\n' +
    '  --tw-ring-offset-color: #fff;\n' +
    '  --tw-ring-color: rgb(59 130 246 / 0.5);\n' +
    '  --tw-blur:  ;\n' +
    '  --tw-brightness:  ;\n' +
    '  --tw-contrast:  ;\n' +
    '  --tw-grayscale:  ;\n' +
    '  --tw-hue-rotate:  ;\n' +
    '  --tw-invert:  ;\n' +
    '  --tw-saturate:  ;\n' +
    '  --tw-sepia:  ;\n' +
    '  --tw-drop-shadow:  ;\n' +
    '  --tw-backdrop-blur:  ;\n' +
    '  --tw-backdrop-brightness:  ;\n' +
    '  --tw-backdrop-contrast:  ;\n' +
    '  --tw-backdrop-grayscale:  ;\n' +
    '  --tw-backdrop-hue-rotate:  ;\n' +
    '  --tw-backdrop-invert:  ;\n' +
    '  --tw-backdrop-opacity:  ;\n' +
    '  --tw-backdrop-saturate:  ;\n' +
    '  --tw-backdrop-sepia:  ;\n' +
    '  --tw-ring-offset-shadow: 0 0 #0000;\n' +
    '  --tw-ring-shadow: 0 0 #0000;\n' +
    '  --tw-shadow: 0 0 #0000;\n' +
    '  --tw-shadow-colored: 0 0 #0000\n' +
    '}\n' +
    '\n' +
    '.container {\n' +
    '  width: 100%\n' +
    '}\n' +
    '\n' +
    '@media (min-width: 640px) {\n' +
    '  .container {\n' +
    '    max-width: 640px\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    '@media (min-width: 768px) {\n' +
    '  .container {\n' +
    '    max-width: 768px\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    '@media (min-width: 1024px) {\n' +
    '  .container {\n' +
    '    max-width: 1024px\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    '@media (min-width: 1280px) {\n' +
    '  .container {\n' +
    '    max-width: 1280px\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    '@media (min-width: 1536px) {\n' +
    '  .container {\n' +
    '    max-width: 1536px\n' +
    '}\n' +
    '\n' +
    '.flex {\n' +
    '  display: flex\n' +
    '}\n' +
    '\n' +
    '.flex-1 {\n' +
    '  flex: 1 1 0%\n' +
    '}\n' +
    '\n' +
    '.text-primary {\n' +
    '  color: rgb(var(--color-primary) / 1)\n' +
    '}\r\n',
  loc: { line: 5, column: 8 },
  data: {
    type: 'SelectorError',
    value: { type: 'PseudoElementExpectedIdent' }
  }
}
```

**Comment by marklawlor** [comment]
You have incorrectly specified your custom plugin. You can see the generated CSS has this line `':root: --color-primary: 255 0 0;\n'`

You need to write your plugin as

`({addBase}) => addBase({'root': {'--color-primary': '255 0 0'}}),`

**Comment by boiboif** [comment]
> You have incorrectly specified your custom plugin. You can see the generated CSS has this line `':root: --color-primary: 255 0 0;\n'`
> 
> You need to write your plugin as
> 
> `({addBase}) => addBase({'root': {'--color-primary': '255 0 0'}}),`

@marklawlor Thanks, problem solved.
there is an error in the document
![image](https://github.com/marklawlor/nativewind/assets/58927554/bc8112c1-00b5-4f9b-a9cc-77e66596b8ae)

**Comment by marklawlor** [comment]
Ah cheers! Yeah I still need to do a pass on he documentation

**Comment by erickreutz** [comment]
Also, it should be ':root' not 'root'
