### ISSUE TITLE
NX Monorepo NativeWind v4

### ISSUE THREAD

**Issue by scott-harrison** [marklawlor/nativewind#627]
Has anyone tried to setup nativewind and is using NX?

Im trying to set it up. However not quite sure how to implement nativewind in the metro config.

Current metro config I have  
```
const { withNxMetro } = require('@nx/react-native');
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const exclusionList = require('metro-config/src/defaults/exclusionList');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const customConfig = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...sourceExts, 'svg'],
    blockList: exclusionList([/^(?!.*node_modules).*\/dist\/.*/]),
    // unstable_enableSymlinks: true,
    // unstable_enablePackageExports: true,
  },
};

module.exports = withNxMetro(mergeConfig(defaultConfig, customConfig), {
  // Change this to true to see debugging info.
  // Useful if you have issues resolving modules
  debug: false,
  // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
  extensions: [],
  // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
  watchFolders: [],
});
```

and according to the nativewind docs, im supposed to do the following:  
[https://www.nativewind.dev/v4/api/with-nativewind](https://www.nativewind.dev/v4/api/with-nativewind)  
```import { withNativeWind } from "native-wind/metro";

module.exports = withNativeWind(config, {  
input: "<relative path to your .css file>",  
});
```

I guess my question is how do i merge them together?

This is my attempt to merge the configs

```
const { withNxMetro } = require('@nx/react-native');
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const exclusionList = require('metro-config/src/defaults/exclusionList');
const { withNativeWind } = require('nativewind/metro');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const customConfig = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...sourceExts, 'svg'],
    blockList: exclusionList([/^(?!.*node_modules).*\/dist\/.*/]),
    // unstable_enableSymlinks: true,
    // unstable_enablePackageExports: true,
  },
};

const nxConfig = withNxMetro(mergeConfig(defaultConfig, customConfig), {
  // Change this to true to see debugging info.
  // Useful if you have issues resolving modules
  debug: false,
  // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
  extensions: [],
  // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
  watchFolders: [],
});

const nativeWindConfig = withNativeWind(nxConfig, {
  input: "./global.css",
});


module.exports = nativeWindConfig
```
However when i do this i get the following error: 
```
nx run mobile-app:run-ios

Starting JS server...
error Cannot read properties of undefined (reading 'sourceExts').
TypeError: Cannot read properties of undefined (reading 'sourceExts')
    at withCssInterop (/Users/me/DEV/sandbox/monorepo/node_modules/react-native-css-interop/dist/metro/index.js:14:45)
    at withNativeWind (/Users/me/DEV/sandbox/monorepo/node_modules/nativewind/dist/metro/index.js:20:46)
    at Object.<anonymous> (/Users/me/DEV/sandbox/monorepo/apps/mobile-app/metro.config.js:38:26)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at module.exports (/Users/me/DEV/sandbox/monorepo/node_modules/cosmiconfig/node_modules/import-fresh/index.js:28:9)
Failed to start the packager server. Error details: undefined

 >  NX   1



 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target run-ios for project mobile-app and 3 task(s) they depend on (9s)

    ✖    1/4 failed
    ✔    3/4 succeeded [0 read from cache]
    ```

**Comment by scott-harrison** [comment]
not even sure the documentation is correct. as it says to import from native-wind/metro. But that doesn't exist

**Comment by scott-harrison** [comment]
Found solution

```
const { withNxMetro } = require('@nx/react-native');
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const exclusionList = require('metro-config/src/defaults/exclusionList');
const { withNativeWind } = require('nativewind/metro');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const customConfig = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...sourceExts, 'svg'],
    blockList: exclusionList([/^(?!.*node_modules).*\/dist\/.*/]),
    // unstable_enableSymlinks: true,
    // unstable_enablePackageExports: true,
  },
};


const nativeWindConfig = withNativeWind(mergeConfig(defaultConfig, customConfig), {
  input: "./global.css",
});

const nxConfig = withNxMetro(nativeWindConfig, {
  // Change this to true to see debugging info.
  // Useful if you have issues resolving modules
  debug: false,
  // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
  extensions: [],
  // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
  watchFolders: [],
});

module.exports = nxConfig
```
