### ISSUE TITLE
v4: TypeError: style.declarations.findLast is not a function (react-native-css-interop)

### ISSUE THREAD

**Issue by rifaldhiaw** [marklawlor/nativewind#800]
**Describe the bug**
I got this error in version nativewind@4.0.25 above. I can confirm in nativewind@4.0.23 it works just fine
```
tailwindcss(native) rebuilding... TypeError: style.declarations.findLast is not a function
    at setStyleForSelectorList (node_modules/react-native-css-interop/src/css-to-rn/index.ts:359:54)
    at extractRule (node_modules/react-native-css-interop/src/css-to-rn/index.ts:178:11)
    at Rule (node_modules/react-native-css-interop/src/css-to-rn/index.ts:82:9)
    at cssToReactNativeRuntime (node_modules/react-native-css-interop/src/css-to-rn/index.ts:76:15)
    at sendUpdate (node_modules/react-native-css-interop/src/metro/poll-updates-server.ts:49:42)
    at Socket.<anonymous> (node_modules/nativewind/src/metro/tailwind-cli.ts:109:17)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
```

**To Reproduce**
- use nativewind latest version in expo sdk 50
- run the expo

**Expected behavior**
Should be able to run

**Expo Snack**
-

**Screenshots**
-

**Additional context**
"expo": "~50.0.6",
"expo-router": "~3.4.7",

**Comment by marklawlor** [comment]
Sorry, the `package.json` is incorrect. NativeWind requires a version of NodeJS that is still supported (minimum Node 18). Node 16 reached end-of-life last year https://github.com/nodejs/release?tab=readme-ov-file#end-of-life-releases

**Comment by rifaldhiaw** [comment]
Ah I see.. turns out I am still using nodejs 16. After upgrading the nodejs, the latest version nativewind works well.
Thanks for your awesome work!
