### ISSUE TITLE
Cannot read properties of undefined (reading 'raw')

### ISSUE THREAD

**Issue by WillSmithTE** [marklawlor/nativewind#821]
**Describe the bug**
Crash on building expo app

**To Reproduce**
1. Run `eas build --platform android --profile prod` (that's my profile name)
2. In eas `run gradlew`, get the following crash
Same on ios

```
[expo-cli] SyntaxError: src/util/global.css: Cannot read properties of undefined (reading 'raw')
[expo-cli] TypeError: Cannot read properties of undefined (reading 'raw')
[expo-cli]     at Object.transform (/Users/me/projects/my-project/app/node_modules/nativewind/dist/metro/transformer.js:16:76)
[expo-cli]     at transformFile (/Users/me/projects/my-project/app/node_modules/metro/src/DeltaBundler/Worker.flow.js:73:36)
[expo-cli]     at Object.transform (/Users/me/projects/my-project/app/node_modules/metro/src/DeltaBundler/Worker.flow.js:48:10)
[expo-cli]     at execFunction (/Users/me/projects/my-project/app/node_modules/jest-worker/build/workers/processChild.js:149:17)
[expo-cli]     at execHelper (/Users/me/projects/my-project/app/node_modules/jest-worker/build/workers/processChild.js:137:5)
[expo-cli]     at execMethod (/Users/me/projects/my-project/app/node_modules/jest-worker/build/workers/processChild.js:140:5)
[expo-cli]     at process.messageListener (/Users/me/projects/my-project/app/node_modules/jest-worker/build/workers/processChild.js:44:7)
[expo-cli]     at process.emit (node:events:518:28)
[expo-cli]     at emit (node:internal/child_process:951:14)
```

**Expected behavior**
Successful build

**Expo Snack**
will try and recreate tomorrow

**Additional context**
v4.0.33
expo 50.0.7

**Comment by WillSmithTE** [comment]
oops saw #796
