### ISSUE TITLE
How to create dynamic css variables ? 

### ISSUE THREAD

**Issue by manjunath-nuveb** [marklawlor/nativewind#839]
I am using nativewind with [rnr](https://rnr-docs.vercel.app/getting-started/introduction/) 
I need to create CSS variables like the following 
```
@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 240 10% 3.9%;
    --card: 0 0% 100%;
    --card-foreground: 240 10% 3.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 240 10% 3.9%;
    --primary: 240 5.9% 10%;
    --primary-foreground: 0 0% 98%;
    --secondary: 240 4.8% 95.9%;
    --secondary-foreground: 240 5.9% 10%;
    --muted: 240 4.8% 95.9%;
    --muted-foreground: 240 3.8% 46.1%;
    --accent: 240 4.8% 95.9%;
    --accent-foreground: 240 5.9% 10%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 0 0% 98%;
    --border: 240 5.9% 90%;
    --input: 240 5.9% 90%;
    --ring: 240 5.9% 10%;
  }

  .dark:root {
    --background: 240 10% 3.9%;
    --foreground: 0 0% 98%;
    --card: 240 10% 3.9%;
    --card-foreground: 0 0% 98%;
    --popover: 240 10% 3.9%;
    --popover-foreground: 0 0% 98%;
    --primary: 0 0% 98%;
    --primary-foreground: 240 5.9% 10%;
    --secondary: 240 3.7% 15.9%;
    --secondary-foreground: 0 0% 98%;
    --muted: 240 3.7% 15.9%;
    --muted-foreground: 240 5% 64.9%;
    --accent: 240 3.7% 15.9%;
    --accent-foreground: 0 0% 98%;
    --destructive: 0 72% 51%;
    --destructive-foreground: 0 0% 98%;
    --border: 240 3.7% 15.9%;
    --input: 240 3.7% 15.9%;
    --ring: 240 4.9% 83.9%;
  }
}
```

But I get these values from API. how to create this dynamically?

**Comment by marklawlor** [comment]
https://www.nativewind.dev/v4/api/vars

**Comment by ospfranco** [comment]
I'm trying to follow [dynamic themes](https://www.nativewind.dev/v4/guides/themes#dynamic-themes), but whenever I add the css variable the tailwind transpilation appears to fail:

When I add the following to my tailwind.config.js

```
colors: {
  primary: 'rgb(var(--color-primary) / <alpha-value>)',
},
```

It fails with:

```
node /Users/osp/Developer/sol/node_modules/tailwindcss/lib/cli.js --input "/Users/osp/Developer/sol/src/global.css" --output "/Users/osp/Developer/sol/node_modules/.cache/nativewind/global.css.macos.css"
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

Rebuilding...
CssSyntaxError: tailwindcss: /Users/osp/Developer/sol/src/global.css:1:1: The `text-neutral-800` class does not exist. If `text-neutral-800` is a custom class, make sure it is defined within a `@layer` directive.
    at Input.error (/Users/osp/Developer/sol/node_modules/postcss/lib/input.js:106:16)
    at AtRule.error (/Users/osp/Developer/sol/node_modules/postcss/lib/node.js:115:32)
    at processApply (/Users/osp/Developer/sol/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:380:29)
    at /Users/osp/Developer/sol/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:551:9
    at /Users/osp/Developer/sol/node_modules/tailwindcss/lib/processTailwindFeatures.js:55:50
    at async Object.Once (/Users/osp/Developer/sol/node_modules/tailwindcss/lib/cli/build/plugin.js:243:17)
    at async LazyResult.runAsync (/Users/osp/Developer/sol/node_modules/postcss/lib/lazy-result.js:261:11)
    at async build (/Users/osp/Developer/sol/node_modules/tailwindcss/lib/cli/build/index.js:49:9) {
  reason: 'The `text-neutral-800` class does not exist. If `text-neutral-800` is a custom class, make sure it is defined within a `@layer` directive.',
  file: '/Users/osp/Developer/sol/src/global.css',
  source: '@tailwind base;\n' +
    '@tailwind components;\n' +
    '@tailwind utilities;\n' +
    '\n' +
    '@layer base {\n' +
    '  .text {\n' +
    '    @apply text-neutral-800 dark:text-neutral-200;\n' +
    '  }\n' +
    '  .darker-text {\n' +
    '    @apply text-neutral-700 dark:text-neutral-400;\n' +
    '  }\n' +
    '  .highlight {\n' +
    '    @apply bg-lightHighlight dark:bg-darkHighlight;\n' +
    '  }\n' +
    '  .border-color {\n' +
    '    @apply border-lightBorder dark:border-darkBorder;\n' +
    '  }\n' +
    '  .subBg {\n' +
    '    @apply bg-subBgLight dark:bg-subBgDark;\n' +
    '  }\n' +
    '}\n',
  line: 1,
  column: 1,
  endLine: 1,
  endColumn: 16,
  input: {
    column: 1,
    endColumn: 16,
    endLine: 1,
    line: 1,
    source: '@tailwind base;\n' +
      '@tailwind components;\n' +
      '@tailwind utilities;\n' +
      '\n' +
      '@layer base {\n' +
      '  .text {\n' +
      '    @apply text-neutral-800 dark:text-neutral-200;\n' +
      '  }\n' +
      '  .darker-text {\n' +
      '    @apply text-neutral-700 dark:text-neutral-400;\n' +
      '  }\n' +
      '  .highlight {\n' +
      '    @apply bg-lightHighlight dark:bg-darkHighlight;\n' +
      '  }\n' +
      '  .border-color {\n' +
      '    @apply border-lightBorder dark:border-darkBorder;\n' +
      '  }\n' +
      '  .subBg {\n' +
      '    @apply bg-subBgLight dark:bg-subBgDark;\n' +
      '  }\n' +
      '}\n',
    url: 'file:///Users/osp/Developer/sol/src/global.css',
    file: '/Users/osp/Developer/sol/src/global.css'
  },
  plugin: 'tailwindcss'
}
```
